
services:
  # SQL Server (baza danych)
  sqlserver:
    build:
      context: .
      dockerfile: C:\Users\Hacce\RiderProjects\WebAppi\CryptoDbDockerService\Dockerfile.sqlserver.yml
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong@Password"
    ports:
      - "1433:1433" # Port SQL Server
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "sqlcmd -S localhost -U sa -P YourStrong@Password -Q \"SELECT 1\"" ]
      interval: 10s
      timeout: 2s
      retries: 6
      start_period: 40s

  # CoinGeckoDockerService (API)
  coingeckodockerservice:
    build:
      context: .
      dockerfile: ./CoinGeckoDockerService/Dockerfile
    container_name: coingecko-api
    depends_on:
      sqlserver:
        condition: service_healthy # Zależy od zdrowia SQL Server
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      # Connection string przekazany jako zmienna środowiskowa
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=CryptoDb;User=sa;Password=YourStrong@Password;TrustServerCertificate=True;"
    ports:
      - "5000:5000" # Port API
    networks:
      - app-network

  # WebAppi
  webappi:
    build:
      context: .
      dockerfile: ./WebAppi/Dockerfile
    container_name: webappi
    depends_on:
      sqlserver:
        condition: service_healthy # Uruchomi się dopiero po "zdrówku" SQL
      coingeckodockerservice:
        condition: service_started # WebAppi uruchomi się dopiero po starcie CoinGeckoDockerService
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=CryptoDb;User=sa;Password=YourStrong@Password;TrustServerCertificate=True;"
    ports:
      - "8080:8080" # Mapowanie portu WebAppi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


  